"""Central OpenSEAL Coordinator combining HBL, eLEARN, EL, and Simulator."""

import asyncio
import json
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional
from seal.config import config
from seal.el.attack_graph import AttackGraph
from seal.el.executor import ELExecutor
from seal.el.scenarios.false_data_injection import create_false_data_injection_campaign
from seal.el.scenarios.unauthorized_setpoint import create_unauthorized_dosing_campaign
from seal.elearn.detector import ELearnDetector
from seal.hbl.engine import HBLEngine
from seal.hbl.parser import HBLParser
from seal.models.alerts import OTAlert
from seal.models.events import OTEvent
from seal.models.playbooks import ResponsePlaybook
from seal.models.topology import AssetStatus, PurdueTopology
from seal.ot_simulator.modbus_server import AsyncModbusServer
from seal.ot_simulator.process_plant import WaterTreatmentPlant
from seal.ot_simulator.sensor_stream import SensorStreamGenerator
from seal.topology_manager import create_default_plant_topology


class OpenSEALSystem:
    """The central unified runtime instance of OpenSEAL (Cyber SEAL clone)."""

    def __init__(self):
        self.config = config
        self.topology: PurdueTopology = create_default_plant_topology()
        self.plant = WaterTreatmentPlant()
        self.playbooks: Dict[str, ResponsePlaybook] = {}

        # 1. HBL Temporal Analytics Engine
        self.hbl = HBLEngine(max_event_history=config.max_event_buffer_size)

        # 2. eLEARN Baseline Deviation Detector
        self.elearn = ELearnDetector(warmup_events=config.elearn_warmup_events)

        # 3. Effects Language (EL) Threat Emulation Executor
        self.el_executor = ELExecutor(
            event_dispatcher=self.dispatch_event,
            state_accessor=self.plant.get_state,
        )

        # 4. Virtual Cyber-Physical Simulator & Modbus Server
        self.modbus_server = AsyncModbusServer(
            plant=self.plant,
            host=config.modbus_host,
            port=config.modbus_port,
            event_callback=self.dispatch_event,
        )
        self.sensor_stream = SensorStreamGenerator(
            plant=self.plant,
            event_callback=self.dispatch_event,
            interval_seconds=config.polling_interval_seconds,
        )

        # Real-time WebSocket / Event subscribers
        self.event_subscribers: List[Callable[[Dict[str, Any]], None]] = []
        self.alert_history: List[OTAlert] = []

        # Wire up alerts from HBL and eLEARN
        self.hbl.subscribe_alerts(self._on_alert_emitted)
        self.elearn.subscribe_alerts(self._on_alert_emitted)

        # Load default playbooks and watchpoints
        self._load_defaults()

    def _load_defaults(self) -> None:
        """Load default playbooks and HBL watchpoints from disk."""
        base_dir = Path(__file__).parent

        # Load playbooks
        pb_dir = base_dir / "playbooks"
        if pb_dir.exists():
            for pb_file in pb_dir.glob("*.json"):
                try:
                    with open(pb_file, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        pb = ResponsePlaybook(**data)
                        self.playbooks[pb.playbook_id] = pb
                except Exception as e:
                    print(f"Error loading playbook {pb_file}: {e}")

        # Load HBL rules
        rules_path = base_dir / "hbl" / "rules.yaml"
        if rules_path.exists():
            try:
                with open(rules_path, "r", encoding="utf-8") as f:
                    watchpoints = HBLParser.parse_yaml(f.read())
                    for wp in watchpoints:
                        self.hbl.register_watchpoint(wp)
            except Exception as e:
                print(f"Error loading HBL rules: {e}")

    def subscribe_ui(self, callback: Callable[[Dict[str, Any]], None]) -> None:
        """Subscribe EdgeReactor UI for streaming events and alerts."""
        self.event_subscribers.append(callback)

    def dispatch_event(self, event: OTEvent) -> None:
        """Single ingress point for all streaming OT events."""
        # 1. Evaluate through Happened-Before Language engine
        self.hbl.process_event(event)

        # 2. Evaluate through eLEARN baseline detector
        self.elearn.process_event(event)

        # 3. Broadcast event to UI subscribers
        msg = {
            "type": "OT_EVENT",
            "data": event.model_dump(),
            "plant_state": self.plant.get_state(),
        }
        for sub in self.event_subscribers:
            try:
                sub(msg)
            except Exception:
                pass

    def _on_alert_emitted(self, alert: OTAlert) -> None:
        """Handle alert generated by HBL or eLEARN."""
        # Attach matching playbook if available
        if alert.mitre_ics_id == "T0836" and "PB-ICS-SETPOINT-01" in self.playbooks:
            alert.playbook = self.playbooks["PB-ICS-SETPOINT-01"]
        elif alert.mitre_ics_id == "T0855" and "PB-ICS-COMM-02" in self.playbooks:
            alert.playbook = self.playbooks["PB-ICS-COMM-02"]

        # Update affected asset status in topology
        for asset_ip in alert.assets_involved:
            target_ips = [asset_ip]
            if asset_ip in ("127.0.0.1", "localhost"):
                target_ips.append("192.168.1.10")  # Virtual PLC-01 in local simulation mode
            for asset in self.topology.assets.values():
                if asset.ip_address in target_ips:
                    asset.status = AssetStatus.COMPROMISED

        self.alert_history.append(alert)

        # Broadcast alert to EdgeReactor UI
        msg = {
            "type": "OT_ALERT",
            "data": alert.model_dump(),
        }
        for sub in self.event_subscribers:
            try:
                sub(msg)
            except Exception:
                pass

    async def start(self, start_simulator: bool = True) -> None:
        """Start OpenSEAL system services."""
        if start_simulator:
            await self.modbus_server.start()
            await self.sensor_stream.start()

    async def stop(self) -> None:
        """Gracefully stop OpenSEAL services."""
        await self.sensor_stream.stop()
        await self.modbus_server.stop()

    async def trigger_emulation(self, campaign_type: str) -> Dict[str, Any]:
        """Trigger an Effects Language (EL) threat emulation scenario."""
        if campaign_type == "chemical_overdose":
            graph = create_unauthorized_dosing_campaign()
        elif campaign_type == "false_data_injection":
            graph = create_false_data_injection_campaign()
        else:
            raise ValueError(f"Unknown campaign type: {campaign_type}")

        # Broadcast start to UI
        for sub in self.event_subscribers:
            try:
                sub({"type": "EMULATION_STARTED", "campaign": graph.to_dict()})
            except Exception:
                pass

        result = await self.el_executor.run_campaign(graph, step_delay_seconds=1.2)

        # Broadcast completion to UI
        for sub in self.event_subscribers:
            try:
                sub({"type": "EMULATION_COMPLETED", "result": result, "campaign": graph.to_dict()})
            except Exception:
                pass

        return result


# Global singleton instance
system = OpenSEALSystem()
